Rework the JDBC TCK
osgi/osgi pull request #537
Opened 2022-12-22 12:31 UTC by laeubi

This do the following:
- merge the method testRegisteredProperties / testMinimumOneDataSourceFactory as it is not compliant to only test there is one valid DSF but all need to implement all required properties
- check that the description (if given) is a string property
- check that the capability is either a string or a String[] type
- join the individual testCapabilityX into one method as actually one needs to check all declared capabilities of one source fulfills the overall contract of at least provide one.

Fix https://github.com/osgi/osgi/issues/529
Fix https://github.com/osgi/osgi/issues/530

@bjhargrave @stbischof please have a look. This should now be consistent to the spec and could test any number of DSF registered.

Additionally this now also check that a DSF at least implements one of the valid values (in contrast to before where it was only checked that one DSF declares any value) and also checks that the property if of the desired type `String+`

2022-12-22 16:52 UTC, bjhargrave requested changes

2022-12-22 16:52 UTC, bjhargrave commented on org.osgi.test.cases.jdbc/src/org/osgi/test/cases/jdbc/junit/JDBCTestCase.java
> +	private static final List<JdbcCapability<?>> ALL_CAPABILITIES = List.of(
We still need to support Java 8. So we cannot use List.of. I am surprise you do not get a compilation error here.

2022-12-22 16:52 UTC, bjhargrave commented on org.osgi.test.cases.jdbc/src/org/osgi/test/cases/jdbc/junit/JDBCTestCase.java
> +				.isInstanceOfAny(String.class, String[].class);
String+ includes a collection of String.

    For example String+, indicates that a String, a String[], and a Collection<String> are all valid forms.

2022-12-22 16:52 UTC, bjhargrave commented on org.osgi.test.cases.jdbc/src/org/osgi/test/cases/jdbc/junit/JDBCTestCase.java
> +			if (FrameworkUtil.createFilter(String.format("(%s=%s)", OSGI_JDBC_CAPABILITY, capability.capability)).match(reference)) {
You have a bundle context here. Use it to create the Filter instead of FrameworkUtil.

2022-12-22 16:52 UTC, bjhargrave commented on org.osgi.test.cases.jdbc/src/org/osgi/test/cases/jdbc/junit/JDBCTestCase.java
> +					String.format("According to '125.2 Database Driver' the property '%s' must be a String if specified", OSGI_JDBC_DRIVER_VERSION));
This sort of test would be better as

```java
assertThat(driverVersion).as(...).isInstanceOf(String.class);
```

2022-12-22 18:07 UTC, laeubi commented
I have now applied the suggested changes.

2022-12-24 14:08 UTC, bjhargrave approved these changes

2022-12-24 14:09 UTC, merged

2022-12-24 14:09 UTC, bjhargrave commented
Thanks for this PR!

2022-12-24 20:33 UTC, stbischof commented
Thx @laeubi good job